name: movie_postgres

services:
  postgres:
    image: postgres:17.6
    container_name: movie_postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: movie_admin  
      POSTGRES_PASSWORD: qazwsxedc
      POSTGRES_DB: movie_database
    ports:
      - "5432:5432"
    volumes:
      - movie_postgres:/var/lib/postgresql/data
    networks:
      - movie_network

networks:
  movie_network:
    driver: bridge

volumes:
  movie_postgres: