apiVersion: v1
kind: Service
metadata:
  name: watchlist-service
  labels:
    app: watchlist-service
spec:
  type: ClusterIP
  selector:
    app: watchlist-service
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
