name: distributed_movie_auth

services:
  postgres:
    image: postgres:17.6
    container_name: ds_movie_auth_pg
    restart: unless-stopped
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: qazwsxedc
      POSTGRES_DB: ds_movie_auth
    ports:
      - "5432:5432"
    volumes:
      - ds_movie_auth_postgres:/var/lib/postgresql/data
    networks:
      - ds_movie_network
  auth-service:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: vdi_system_admin_app
    restart: unless-stopped
    env_file:
      - .env.local
    ports:
      - "3000:3000"
    networks:
      - ds_movie_network
    depends_on:
      - postgres

volumes:
  ds_movie_auth_postgres:

networks:
  ds_movie_network:
    driver: bridge
