apiVersion: apps/v1
kind: Deployment
metadata:
  name: comment-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: comment-service
  template:
    metadata:
      labels:
        app: comment-service
    spec:
      containers:
        - name: comment-service
          image: draculastream/comment-service:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          env:
            - name: SERVICE_PORT
              valueFrom:
                configMapKeyRef:
                  name: comment-service-config
                  key: SERVICE_PORT
            - name: MONGO_URI
              valueFrom:
                configMapKeyRef:
                  name: comment-service-config
                  key: MONGO_URI
            - name: MONGO_DB
              valueFrom:
                configMapKeyRef:
                  name: comment-service-config
                  key: MONGO_DB
            - name: MONGO_COLLECTION
              valueFrom:
                configMapKeyRef:
                  name: comment-service-config
                  key: MONGO_COLLECTION
            - name: KAFKA_BROKERS
              valueFrom:
                configMapKeyRef:
                  name: comment-service-config
                  key: KAFKA_BROKERS
            - name: KAFKA_TOPIC_COMMENT_CREATED
              valueFrom:
                configMapKeyRef:
                  name: comment-service-config
                  key: KAFKA_TOPIC_COMMENT_CREATED
            - name: KAFKA_TOPIC_COMMENT_REPLIED
              valueFrom:
                configMapKeyRef:
                  name: comment-service-config
                  key: KAFKA_TOPIC_COMMENT_REPLIED
          readinessProbe:
            httpGet:
              path: /ready
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 15
            failureThreshold: 3
          livenessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 20
            failureThreshold: 3
---
apiVersion: v1
kind: Service
metadata:
  name: comment-service
spec:
  selector:
    app: comment-service
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: ClusterIP