# 1. AUTH SERVICE (auth.dracula.com)
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: auth-ingress
  annotations:
    kubernetes.io/ingress.class: nginx
    # Allow headers for auth
    nginx.ingress.kubernetes.io/cors-allow-credentials: "true"
    nginx.ingress.kubernetes.io/cors-allow-origin: "http://dracula.com"
spec:
  rules:
    - host: auth.dracula.com # <--- NEW SUBDOMAIN
      http:
        paths:
          # Send EVERYTHING on this subdomain to Auth Service
          - path: /
            pathType: Prefix
            backend:
              service:
                name: auth-service
                port:
                  number: 3000

---
# 2. MAIN PAGE, COMMENT & CONSUMET (dracula.com)
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: main-ingress
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /$2
    nginx.ingress.kubernetes.io/proxy-body-size: "10m"
spec:
  rules:
    - host: dracula.com
      http:
        paths:
          # Consumet API
          - path: /anime(/|$)(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: consumet-api
                port:
                  number: 3000
          # Maps dracula.com/api/comments -> comment-service:8080
          - path: /api/comments(/|$)(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: comment-service
                port:
                  number: 8080

          # Main Page (Catch-all)
          - path: /()(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: main-page
                port:
                  number: 3000
---
# 3. ACCOUNT SERVICE
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: account-ingress
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/proxy-body-size: "10m"
spec:
  rules:
    - host: account.dracula.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: account-service
                port:
                  number: 8000
---
# 4. MinIO
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: minio-ingress
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/proxy-body-size: "100m" # Allow larger uploads via console
spec:
  rules:
    - host: files.dracula.com # Map this in your hosts file
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: minio-service
                port:
                  number: 9001 # Console port
---
#5. Watchlist service
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: watchlist-ingress
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/cors-allow-credentials: "true"
    nginx.ingress.kubernetes.io/cors-allow-origin: "http://dracula.com, http://auth.dracula.com"
spec:
  rules:
    - host: watchlist.dracula.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: watchlist-service
                port:
                  number: 8000
