apiVersion: apps/v1
kind: Deployment
metadata:
  name: main-page
spec:
  replicas: 2
  selector:
    matchLabels:
      app: main-page
  template:
    metadata:
      labels:
        app: main-page
    spec:
      containers:
        - name: main-page
          image: myuser/main-page:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 3000
          env:
            # Public URL for Client-Side Redirects
            - name: BETTER_AUTH_URL
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: BETTER_AUTH_URL
            # Internal URL for Server-Side Session Fetching
            - name: INTERNAL_AUTH_URL
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: AUTH_SERVICE_INTERNAL
            - name: NEXT_PUBLIC_BETTER_AUTH_URL
              value: "http://dracula.com"
            - name: NEXT_PUBLIC_ACCOUNT_API_URL
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: NEXT_PUBLIC_ACCOUNT_API_URL
---
apiVersion: v1
kind: Service
metadata:
  name: main-page
spec:
  selector:
    app: main-page
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
