apiVersion: v1
kind: Secret
metadata:
    name: app-secrets
type: Opaque
stringData:
    BETTER_AUTH_SECRET: ENC[AES256_GCM,data:Sv3W1lFZkOBWcHwIBUrJ41UCQgDukf0JvlhU3oS8A5cF3N9HMuXy8icOsNc=,iv:jjMkrQ3Jc1eyRlX/wYDajl4Ss37MN/PAkyiB4S2vDw0=,tag:ZqhllR053XmBrwZdQKEfkg==,type:str]
    DATABASE_URL: ENC[AES256_GCM,data:YkGqAUgxANVcI6ZmtP8Ct378C8CSITtU1JkWGlzSdWn86qWZM/Fa/J/Fk5+O00rV7ShH3KYTnifMfP4TP0g/QHM7UV1uT0YO+jMm+ktj8l4=,iv:8c/b1A+QQ0vl7DMmOmSdaXhVlSzEjTPCRi6/GnPSUX0=,tag:VC6WgQgAaDOhOWyz9W/tiA==,type:str]
    GOOGLE_CLIENT_ID: ENC[AES256_GCM,data:+JhAt2iufamznl++CGIslFQggscRx1JPUYd5Ya0xuig3ZYulNHQvANF17ndKXFCPE8IoHXjY7njb93RyfX6ZNY7WmRFg69YK,iv:XhyLDiHuu3Ocdcq80wpyCDkjTYXYlVMyw4SsxCw77Ys=,tag:5xRMoExasBBHVVcsuCuLGA==,type:str]
    GOOGLE_CLIENT_SECRET: ENC[AES256_GCM,data:gIOX7Q1j9IyzwZWTKOQPmfq7aF2ycutuJ8oLj0/zu3il2gc=,iv:n6Re1xps1/+CNyn8NMkpW0Hcqubp1iE7X2U+3x+L/Os=,tag:AKRKjL2CjeNrS8bQtyBoSw==,type:str]
sops:
    age:
        - recipient: age1a73gfhevyxasn5xttuqpzz2trfzggcnvx9xn4a9ka7xx7sx00dsq2zduja
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBhRDJXSndrN3ZFMVFTTk1N
            d0dNRFZmQkcybUxFTTNMVDFYK1FGRjdqZUFnCjBJb2hRd3l0aER1OW9vbFZhZ3M3
            UHE3RGViaERKL3hrWFZjbkpHdFBvTjgKLS0tIDZXd2htOUxMZjUrZW5nbG9vd2E3
            cHhVdmc5UnR5bDhqZWx3OHg0bk1vSEkKbVOt20LQ6ufd7NE2Eq4oC7SEwb8gpIUY
            Zh3B/SlS0uq/hpMWmw9cfLUUakkZHOdMlTRshF3UJt0uQf7vMmI+PA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-10T23:39:59Z"
    mac: ENC[AES256_GCM,data:gRbAB/FR5DbjpoCOOvBhx280Cnp/GwNFnlrMwXDR6gWdRbRh9CBZzOaUt7aJvZjgzsNjsGndRTXj8qqPDJoTqS/o9mSwhapL3/v2HclWKFYa+wiF3MTLc36EbRuanUxcaFac/USoY/8WZ2hHteciwLdoouAcymue9DEAAihSyDg=,iv:XCnWANys2ICkEiO2XyaLJwEalobgTsj6U137f3gFeRw=,tag:GNJC22/WdNFHFlwcWY40Cg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
