apiVersion: v1
kind: Secret
metadata:
    name: app-secrets
type: Opaque
stringData:
    BETTER_AUTH_SECRET: ENC[AES256_GCM,data:hVyUrrssHgqVHJBKG+y1FTeUqYUG7l8sC49sn+6s4sOwAgKeLZOgg6xMB0o=,iv:i1O8hbz5erDKOZ4NTWrJf3i/KGrf0mHs7aiRQnnXbmw=,tag:JNHqIc78/W5rnNHjsuALAg==,type:str]
    DATABASE_URL: ENC[AES256_GCM,data:b/dmOkH6sK9waflebD8NEghKbLAwNh5XrATiFrY+Wd9QKsWmI9SomZYmmFXtkKYXyejcbY8roueQDFnlEmg/Bv0DkqqNUhDhHcC0M7OXSA4=,iv:Om6AhN9x2s/pTFNLPeVj1wXOuD+v6+mHWZlgjZBXafk=,tag:GSSVTTdWscjAXFbhOVYiqg==,type:str]
    GOOGLE_CLIENT_ID: ENC[AES256_GCM,data:VovZjmfWYC5UqUhfThFhGQSMDVRG2TBfihX5s77S0SpeVzFoKfc8FI8rtfJ/oKXaFpJXFYyRSFxIw1NjUXYJipG+IYd6A/u+,iv:AkrjzxgVKOZ9aHxJJDSw4wwc3XC4KJ3b3V1k32zz7zE=,tag:h0YWiOEradBBNpmpM/cLlw==,type:str]
    GOOGLE_CLIENT_SECRET: ENC[AES256_GCM,data:+z4FLdisFSCur2E60HRLHzxRynvMw4BbWoqNKmPBawwNinI=,iv:P1NGYsczkRTbmYom17kxrLSOHRQNf2gH9OYkG5mNKQI=,tag:0yRi+RHwRrjgBj871RhbFA==,type:str]
    POSTGRES_PASSWORD: ENC[AES256_GCM,data:97ekbeot2JI6,iv:oXQUbnhHr7nV1NfFawszXU0fUJrQe5gT+vLePkkR1Hw=,tag:CfDfqpUZA/57y6whb+8DTA==,type:str]
    MINIO_ROOT_USER: ENC[AES256_GCM,data:rmYz9P+m5yUPsw==,iv:lKsxCkaPIYPl1gaqtea5/sSFO2bAJyUGkZjtt6pbBDY=,tag:3j+5txsnNOsEEWRPAlZV5w==,type:str]
    MINIO_ROOT_PASSWORD: ENC[AES256_GCM,data:JaTkRk9RpJ5Chg==,iv:M2Xh1txJIzqU1t/CaYgjM10wudrXPyOlKoWl2pT9SGY=,tag:d87djQwDjtpJr1kaXTr0qg==,type:str]
sops:
    age:
        - recipient: age1a73gfhevyxasn5xttuqpzz2trfzggcnvx9xn4a9ka7xx7sx00dsq2zduja
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBCcXZSUmtjZDlPMHNyVnFC
            UlozK2Fyd1VmRmgrWllMbWJuYy91MGtMbXpNClpCRE53K094S3RzZlBTUlJxVmlP
            SHpsMng3WGJraTlvZW5SOENPdmhvd0UKLS0tIDdUVy9pL2dzanlyb3laMm11MnF0
            bmJvL2xFeUo0Nk4xaFNJVGFyM1J1ZUEK9mbZeLUOCFNpV8CCtA/XsFrFsaTV+4pS
            N76+D+JQQSvFHJUe6yEEBiQYC+Eu4QliGNVcfWw6P7NNrpbmdgzRTg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-19T14:41:50Z"
    mac: ENC[AES256_GCM,data:F5zoFApJDo+OPwJQO4jx9y5M4dOKR2JCUJevs8y97JPfq3h8x8SePeHaenysg4C0j2d7vm+FR39O4dlhMsnH4WXdDaKUdXPODQIRCuPyVC1WOltRUpIIn2P+aniHtdjynkzxnSwAdbKSEBc3Y4RgORcXOiSlTE0e32yraFvhuFo=,iv:FEKjrfiO1l4KiYhUMUBL1lM9gS4yhm+3cxJOHEYXY3E=,tag:SovFRfo0GHFIsZfMsPPUcA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
