apiVersion: v1
kind: Secret
metadata:
    name: app-secrets
type: Opaque
stringData:
    BETTER_AUTH_SECRET: ENC[AES256_GCM,data:X4ERwQlozFqHR27cnH4KDYCpszhoLrDSzQGh2BHXKk7irGSe6mrZ+2oFukU=,iv:RdWawqWaD0Th4rioHfd4FtOhkZJS5tguR84RRCzwYqo=,tag:NP3bJQmXV1M8viTnuUpWQQ==,type:str]
    DATABASE_URL: ENC[AES256_GCM,data:FS9hzea9JE5v+Gdek1/dXs1YkqNZou3h0Uz0yP6E6+om35AmL9765SIaYnBwKh0bE977jINjDaHEiuTEQ9mY5DFMojV4cfnTJt9EU7kaptU=,iv:74ePcBv/ULfrWvcwlN+DpdZrQFvy5kSYOPVvsgw8Tx4=,tag:1tdzt2RXxNRCO8WL7JvSjw==,type:str]
    GOOGLE_CLIENT_ID: ENC[AES256_GCM,data:e2OVp20CIdpx9oCcUOBUQfUTV/CtVS51Kxt5amiM3nyyauDOiluq2tuH2UzqGdotJOO3vYxF2Olgq9KyKr6FAsFvSv9AH7e5,iv:4s0rJylSishsnjmblz1Bj8TXiZg1I4DdeL9A+AQTZS0=,tag:bk8C47WYEJTfPTp8wAupDA==,type:str]
    GOOGLE_CLIENT_SECRET: ENC[AES256_GCM,data:C8oNcONidd5oiqzI52XhUlZ9vbS5vQxmdyXPU/zhTHIa72Y=,iv:w7ZaG2o9O1Iu24YqoGrag5awsXaPdwRO+ywY1lAf1EE=,tag:w5WE67KGJB1SUsT+kDy02A==,type:str]
    POSTGRES_PASSWORD: ENC[AES256_GCM,data:ImBQxwmrlFv1,iv:IN+H6JvUoeBH9xgVdSrvmWtH/kzfPmepElz9vllyL4o=,tag:EdBDGgMyEGh5f8dhpWR8lw==,type:str]
    MINIO_ROOT_USER: ENC[AES256_GCM,data:ZHW4RdwbRKnnXQ==,iv:EkRaufKf2ccChPOUX2Wd7mwyVCNM0SgSCrZEywaj9ww=,tag:kiWP2yGvMttEDSWNucTryQ==,type:str]
    MINIO_ROOT_PASSWORD: ENC[AES256_GCM,data:C8nR5AG/O/sYng==,iv:fPmzfOjTOoTaQ3T3kaSp8cr5qjtUtpN8SVN75okMawA=,tag:4w0eRvoJSN1Vdf3B7kzBHQ==,type:str]
    SERVICE_PORT: ENC[AES256_GCM,data:FvCkgA==,iv:v1t6RJsAX9ZofMrZN5G4LD4YHcDjuMbH4FOZ+PPCcfU=,tag:MorjuZW0qnMLmyyMBLAumg==,type:str]
    MONGO_URI: ENC[AES256_GCM,data:xVJsMsvQa/3RZclw0ZiLq/WWJFiHwRXzYvKkt+FTgg==,iv:TmwKEXfVMIQsV8RzPsuhE+PEmSm903hsnvcL1mVzb0E=,tag:EWWpTGQGxirY/NRTM9NDbQ==,type:str]
sops:
    age:
        - recipient: age1a73gfhevyxasn5xttuqpzz2trfzggcnvx9xn4a9ka7xx7sx00dsq2zduja
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqeXZTakR0SkMzMDROVjEz
            aFNJeHA2clkvYUVuaktUdzhoK0dML3VpdGhnClpONzVHOUlRUGFuM2JaQWFmV25C
            Z1p0TmxjUFdub2lzdXR5R0lWYVV3ZHMKLS0tIEJweERtZGtLbGlwOUxuNmUwbmI4
            eS8wMG5RVnV5bG90cWV1QUpEU2RFV2MKHZ5EaBdg2PMEO/3ziDSNjXBDXEVDt/4X
            TFMGRQhGyvYtAaAZ9yW7Kx2tfhdqmLBBfgMNeROkHgHMeMwcKeMw1A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-19T21:55:11Z"
    mac: ENC[AES256_GCM,data:ODK7/mH3O2a9l8SsvIGe9L/Gy+ZvjgEfXgCsv8NUalo34GPblExFQAROYEIL3uT8DxndJczhY14JH2AVp3PIpsqW3tnISAsYdcuew638tjT8CVVHXljG3RVer/AgSzOazUUhqRk7YPRImjcxP+TgyLmn7jCYfo/t13t7tS8Chrc=,iv:cnG5D/p1E+ntR92a5xTZ9YfNVJKRC1NQcKpHY3nGzSU=,tag:4K6IbPzoPZaNSdhZE/qvDA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
